#!/usr/bin/python3

import amulet
import requests
import unittest
import errno


class TestCharm(unittest.TestCase):
    def setUp(self):
        self.d = amulet.Deployment(series='trusty')
        self.d.add('logstash', 'cs:trusty/logstash-0')
        self.d.add('zulu8', 'cs:trusty/zulu8-2')
        self.d.relate('zulu8:java', 'logstash:java')
        self.d.expose('logstash')
        self.d.add('conf-file' charm='logstash-conf-d')
        self.d.relate('conf-file', 'logstash')

        self.d.setup(timeout=900)
        self.d.sentry.wait()

        self.unit = self.d.sentry['conf-file'][0]



    def test_service(self):

        # Conf file exists
        subject = self.d.sentry['conf-file'][0]
        subject.file('/etc/logstash/conf.d/conf-file.conf')


        self.d.unrelate('conf-file', 'logstash')
        self.d.setup(timeout=60)
        self.d.sentry.wait()
        except:
            subject.file('/etc/logstash/conf.d/conf-file.conf')
        except IOError as e:
            if e.errno == errno.ENOENT:
                pass
            else:
                raise e


if __name__ == '__main__':
    unittest.main()
